### ISSUE TITLE
NonIssue

### ISSUE THREAD

**Issue by LuminousRedNova** [csoulakian/cs330s16p1#1]
I just want to say that your documentation is amazing! The little notes for everything actually helps me to understand regex a little more. The only thing I can suggest is allowing the program to just pull mentions, topics, or URLs out of the tweet rather than all at once.

**Comment by csoulakian** [comment]
Thanks! I'm glad the documentation was helpful, especially the regex. 

The main output is a bit rusty, as I've been switching off between having it print the HashMap and the string array of words to help with testing. The unit tests show that you can access each list of mentions, topics, and urls individually. The main method I wrote was a little something extra so the user can run the program with his/her own sample tweet. I'm not sure if/why a user would parse a tweet only looking for the mentions, topics, or urls, but I would have to scan in the option separately from the tweet. Instead of providing a menu and making the user specify what to look for, I give them the entire tweet parsed. Do you think it would it help if I change the output to print some context rather than simply the HashMap in its basic form?

**Comment by LuminousRedNova** [comment]
It might be, and a for instance with only parsing for one thing. You could be doing metrics trying to find out who is mentioned most in a list of tweets etc. and only want that one part.

**Comment by csoulakian** [comment]
Ok, got it. That might be a nice feature to add in the future!
